"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.chartRefResponseMappingLocalOverrideOkYaml = exports.nodeParamsResponseMappingOnlyYaml = exports.datasourceParamsResponseMappingYaml = exports.nodeParamsResponseMappingYaml = exports.tableRefResponseMappingInheritedCompleteYaml = exports.chartRefResponseMappingInheritedMissingListYaml = exports.tableRefResponseMappingInheritedMissingListYaml = exports.validAllReferencesYaml = exports.invalidTargetTableYaml = exports.danglingDataRefYaml = exports.uploadActionRefWrongTypeYaml = exports.missingSubmitActionTargetYaml = exports.unknownContextNamespaceYaml = exports.nodePermissionSelfYaml = exports.tableActionFormScopeSelfYaml = exports.formVisibleWhenSelfYaml = exports.tableActionPermissionSelfYaml = exports.tableRefResponseMappingMissingListYaml = exports.tableFormScopeReactionForbiddenStateYaml = exports.tableRowReactionForbiddenStateYaml = exports.tableVisibleWhenMissingWhenYaml = exports.missingRowRequestCapabilityYaml = exports.missingUploadCapabilityYaml = exports.missingRowScopeYaml = void 0;
exports.missingRowScopeYaml = "\nmeta:\n  pageId: bad_row_scope\n  title: Bad Row Scope\n  protocolVersion: \"0.2\"\nbody:\n  type: table\n  props:\n    rowKey: id\n    pagination:\n      mode: server\n    columns:\n      - field: id\n        label: ID\n        visibleWhen:\n          when: \"$row.id == '1'\"\n  data:\n    source: api\n    url: /api/items\n";
exports.missingUploadCapabilityYaml = "\nmeta:\n  pageId: upload_page\n  title: Upload Page\n  protocolVersion: \"0.2\"\nbody:\n  type: upload\n  props:\n    label: Attachment\n    actionRef: uploadAttachment\nactions:\n  uploadAttachment:\n    type: upload\n    method: POST\n    url: /api/upload\n";
exports.missingRowRequestCapabilityYaml = "\nmeta:\n  pageId: row_request_page\n  title: Row Request Page\n  protocolVersion: \"0.2\"\nactions:\n  approveOrder:\n    type: request\n    method: POST\n    url: /api/orders/{orderId}/approve\nbody:\n  type: table\n  props:\n    rowKey: orderId\n    pagination:\n      mode: server\n    columns:\n      - field: orderId\n        label: Order ID\n    actions:\n      - key: approve\n        label: Approve\n        actionRef: approveOrder\n        requestMapping:\n          path:\n            orderId: $row.orderId\n  data:\n    source: api\n    url: /api/orders\n";
exports.tableVisibleWhenMissingWhenYaml = "\nmeta:\n  pageId: table_visiblewhen_missing_when\n  title: Table VisibleWhen Missing When\n  protocolVersion: \"0.2\"\nbody:\n  type: table\n  props:\n    rowKey: id\n    pagination:\n      mode: server\n    columns:\n      - field: id\n        label: ID\n        visibleWhen:\n          scope: row\n          dependencies: [id]\n  data:\n    source: api\n    url: /api/items\n";
exports.tableRowReactionForbiddenStateYaml = "\nmeta:\n  pageId: table_row_reaction_forbidden_state\n  title: Table Row Reaction Forbidden State\n  protocolVersion: \"0.2\"\nbody:\n  type: table\n  props:\n    rowKey: id\n    pagination:\n      mode: server\n    columns:\n      - field: id\n        label: ID\n        reactions:\n          - scope: row\n            dependencies: [id]\n            when: \"$row.id == '1'\"\n            fulfill:\n              required: true\n  data:\n    source: api\n    url: /api/items\n";
/** 表格列 scope:form 下仍禁止 required/value（0044/V167） */
exports.tableFormScopeReactionForbiddenStateYaml = "\nmeta:\n  pageId: table_form_scope_reaction_forbidden_state\n  title: Table Form Scope Reaction Forbidden State\n  protocolVersion: \"0.2\"\nbody:\n  type: table\n  props:\n    rowKey: id\n    pagination:\n      mode: server\n    columns:\n      - field: id\n        label: ID\n        reactions:\n          - dependencies: []\n            when: \"$context.features.highlight == true\"\n            fulfill:\n              value: null\n              required: true\n    actions:\n      - key: edit\n        label: \u7F16\u8F91\n        reactions:\n          - dependencies: []\n            when: \"$context.user.roles contains 'admin'\"\n            fulfill:\n              value: null\n  data:\n    source: api\n    url: /api/items\n";
exports.tableRefResponseMappingMissingListYaml = "\nmeta:\n  pageId: table_ref_response_mapping_missing_list\n  title: Table Ref ResponseMapping Missing List\n  protocolVersion: \"0.2\"\ndatasources:\n  orders:\n    source: api\n    url: /api/orders\nbody:\n  type: table\n  props:\n    rowKey: id\n    pagination:\n      mode: server\n    columns:\n      - field: id\n        label: ID\n  data:\n    source: ref\n    ref: orders\n    responseMapping:\n      total: result.total\n";
exports.tableActionPermissionSelfYaml = "\nmeta:\n  pageId: table_action_permission_self\n  title: Table Action Permission Self\n  protocolVersion: \"0.2\"\nbody:\n  type: table\n  props:\n    rowKey: id\n    pagination:\n      mode: none\n    columns:\n      - field: id\n        label: ID\n    actions:\n      - key: approve\n        label: Approve\n        permissions:\n          view: \"$self == true\"\n  data:\n    source: static\n    value: []\n";
/** 表单内 visibleWhen 误用 $self（0045/V175） */
exports.formVisibleWhenSelfYaml = "\nmeta:\n  pageId: form_visiblewhen_self\n  title: Form VisibleWhen Self\n  protocolVersion: \"0.2\"\nbody:\n  type: form\n  props:\n    submitAction: save\n  children:\n    - type: input\n      props:\n        field: name\n        label: Name\n      visibleWhen:\n        dependencies: []\n        when: \"$self == true\"\nactions:\n  save:\n    type: request\n    method: POST\n    url: /api/save\n";
/** 表格 actions scope:form 误用 $self（0045/V176） */
exports.tableActionFormScopeSelfYaml = "\nmeta:\n  pageId: table_action_form_self\n  title: Table Action Form Scope Self\n  protocolVersion: \"0.2\"\nbody:\n  type: table\n  props:\n    rowKey: id\n    pagination:\n      mode: server\n    columns:\n      - field: id\n        label: ID\n    actions:\n      - key: approve\n        label: Approve\n        visibleWhen:\n          scope: form\n          dependencies: []\n          when: \"$self == true\"\n  data:\n    source: api\n    url: /api/items\n";
exports.nodePermissionSelfYaml = "\nmeta:\n  pageId: node_permission_self\n  title: Node Permission Self\n  protocolVersion: \"0.2\"\nbody:\n  type: input\n  props:\n    field: title\n    label: Title\n  permissions:\n    view: \"$self == true\"\n";
exports.unknownContextNamespaceYaml = "\nmeta:\n  pageId: unknown_context_namespace\n  title: Unknown Context Namespace\n  protocolVersion: \"0.2\"\nbody:\n  type: input\n  props:\n    field: title\n    label: Title\n  permissions:\n    view: \"$context.tenant.id == 't1'\"\n";
exports.missingSubmitActionTargetYaml = "\nmeta:\n  pageId: missing_submit_action\n  title: Missing SubmitAction Target\n  protocolVersion: \"0.2\"\nactions:\n  someAction:\n    type: request\n    method: POST\n    url: /api/submit\nbody:\n  type: form\n  props:\n    title: Missing Target\n    submitAction: nonExistentAction\n  children:\n    - type: input\n      props:\n        field: name\n        label: Name\n";
exports.uploadActionRefWrongTypeYaml = "\nmeta:\n  pageId: upload_wrong_type\n  title: Upload Wrong ActionRef Type\n  protocolVersion: \"0.2\"\n  requiredCapabilities:\n    - actions.upload\nactions:\n  myUpload:\n    type: request\n    method: POST\n    url: /api/upload\nbody:\n  type: upload\n  props:\n    label: Attachment\n    actionRef: myUpload\n";
exports.danglingDataRefYaml = "\nmeta:\n  pageId: dangling_data_ref\n  title: Dangling Data Ref\n  protocolVersion: \"0.2\"\nbody:\n  type: table\n  props:\n    rowKey: id\n    pagination:\n      mode: none\n    columns:\n      - field: id\n        label: ID\n  data:\n    source: ref\n    ref: nonExistentDatasource\n";
exports.invalidTargetTableYaml = "\nmeta:\n  pageId: invalid_target_table\n  title: Invalid TargetTable\n  protocolVersion: \"0.2\"\nbody:\n  type: form\n  props:\n    title: Search Form\n    mode: search\n    targetTable: missingTableId\n  children:\n    - type: input\n      props:\n        field: keyword\n        label: Keyword\n";
exports.validAllReferencesYaml = "\nmeta:\n  pageId: valid_all_refs\n  title: Valid All References\n  protocolVersion: \"0.2\"\n  requiredCapabilities:\n    - actions.upload\ndatasources:\n  orders:\n    source: api\n    url: /api/orders\nactions:\n  submitOrder:\n    type: request\n    method: POST\n    url: /api/orders\n  uploadAttach:\n    type: upload\n    method: POST\n    url: /api/upload\nbody:\n  type: grid\n  props:\n    columns: 2\n  children:\n    - type: form\n      id: searchForm\n      props:\n        title: Search\n        mode: search\n        targetTable: orderTable\n      children:\n        - type: input\n          props:\n            field: keyword\n            label: Keyword\n    - type: table\n      id: orderTable\n      props:\n        rowKey: id\n        pagination:\n          mode: server\n        columns:\n          - field: id\n            label: ID\n      data:\n        source: ref\n        ref: orders\n";
exports.tableRefResponseMappingInheritedMissingListYaml = "\nmeta:\n  pageId: table_ref_inherited_missing_list\n  title: Table Ref Inherited Missing List\n  protocolVersion: \"0.2\"\ndatasources:\n  orders:\n    source: api\n    url: /api/orders\n    responseMapping:\n      total: result.total\nbody:\n  type: table\n  props:\n    rowKey: id\n    pagination:\n      mode: server\n    columns:\n      - field: id\n        label: ID\n  data:\n    source: ref\n    ref: orders\n";
exports.chartRefResponseMappingInheritedMissingListYaml = "\nmeta:\n  pageId: chart_ref_inherited_missing_list\n  title: Chart Ref Inherited Missing List\n  protocolVersion: \"0.2\"\ndatasources:\n  sales:\n    source: api\n    url: /api/sales\n    responseMapping:\n      total: result.total\nbody:\n  type: chart\n  props:\n    chartType: bar\n    xField: date\n    yField: amount\n  data:\n    source: ref\n    ref: sales\n";
exports.tableRefResponseMappingInheritedCompleteYaml = "\nmeta:\n  pageId: table_ref_inherited_complete\n  title: Table Ref Inherited Complete\n  protocolVersion: \"0.2\"\ndatasources:\n  orders:\n    source: api\n    url: /api/orders\n    responseMapping:\n      list: result.records\n      total: result.total\nbody:\n  type: table\n  props:\n    rowKey: id\n    pagination:\n      mode: server\n    columns:\n      - field: id\n        label: ID\n  data:\n    source: ref\n    ref: orders\n";
exports.nodeParamsResponseMappingYaml = "\nmeta:\n  pageId: node_params_response_mapping\n  title: Node Params ResponseMapping\n  protocolVersion: \"0.2\"\nbody:\n  type: table\n  props:\n    rowKey: id\n    pagination:\n      mode: server\n    columns:\n      - field: id\n        label: ID\n  data:\n    source: api\n    url: /api/orders\n    params:\n      status: pending\n      responseMapping:\n        list: result.records\n    responseMapping:\n      list: result.records\n";
exports.datasourceParamsResponseMappingYaml = "\nmeta:\n  pageId: ds_params_response_mapping\n  title: Datasource Params ResponseMapping\n  protocolVersion: \"0.2\"\ndatasources:\n  orders:\n    source: api\n    url: /api/orders\n    params:\n      status: pending\n      responseMapping:\n        list: result.records\n    responseMapping:\n      list: result.records\n      total: result.total\nbody:\n  type: table\n  props:\n    rowKey: id\n    pagination:\n      mode: server\n    columns:\n      - field: id\n        label: ID\n  data:\n    source: ref\n    ref: orders\n";
exports.nodeParamsResponseMappingOnlyYaml = "\nmeta:\n  pageId: node_params_rm_only\n  title: Node Params RM Only\n  protocolVersion: \"0.2\"\nbody:\n  type: table\n  props:\n    rowKey: id\n    pagination:\n      mode: none\n    columns:\n      - field: id\n        label: ID\n  data:\n    source: api\n    url: /api/items\n    params:\n      responseMapping:\n        list: result.records\n";
exports.chartRefResponseMappingLocalOverrideOkYaml = "\nmeta:\n  pageId: chart_ref_local_override_ok\n  title: Chart Ref Local Override OK\n  protocolVersion: \"0.2\"\ndatasources:\n  sales:\n    source: api\n    url: /api/sales\n    responseMapping:\n      total: result.total\nbody:\n  type: chart\n  props:\n    chartType: bar\n    xField: date\n    yField: amount\n  data:\n    source: ref\n    ref: sales\n    responseMapping:\n      list: result.items\n";
